### ISSUE TITLE
Mouse cursor disappears after opening inventory.

### ISSUE THREAD

**Issue by seanohue** [ajxs/jsFO#32] opened 2015-11-11 19:43 UTC

**Comment by ajxs** [comment] 2015-11-11 23:27
Thanks for reporting the bug! 
Should be resolved with latest commit.
It was an issue caused by a previous change in how sprites are referenced by the SpriteObject prototype. The previous system generated a string to reference the correct FRM file based on the object's FID value, on a frame by frame basis. The new system computes this only upon instantiation and when animations are changed, and saves a pointer to the resulting sprite object in SpriteObject.anim.img. The InventoryState class was just using the older style still. Updated that and it appears fixed.

**Closed as completed by ajxs** 2015-11-11 23:27 UTC

**Comment by seanohue** [comment] 2015-11-12 00:19
No problem. I'm using the gh-pages version of the project to try to find bugs, should I be cloning the project down and running that version instead or is the gh-pages version up to date?

**Comment by ajxs** [comment] 2015-11-12 00:25
The gh-pages branch is typically kept up to date. I'll do a merge now.
There's alot of small bugs present, and all of the 'use' functionality on doors,etc is preliminary and will have to completely overhauled the day I decide to implement the actual game scripting. 
Definitely keep reporting any bugs though! And feel free to ask any questions regarding how the engine works!

**Comment by ajxs** [comment] 2015-11-12 00:26
It'd probably be a good idea for me to actually finish up some documentation for the wiki. In case anyone wants to pick up the project from me.
